[package]
org = "2k3je"
name = "server"
version = "0.1.0"
distribution = "2201.7.1"

[build-options]
observabilityIncluded = true


[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.34"

[[platform.java11.dependency]]
path = "mysql-connector-j-8.1.0.jar”